Repository openstack-k8s-operators/cinder-operator, pull requests merged in 2022-09, with the labels that each got.

#10 Added OWNERS file required by PROW.
  OWNERS
Labels: lgtm

#12 Fix Cinder services hanging
  api/v1beta1/cinder_types.go
  api/v1beta1/cinderapi_types.go
  api/v1beta1/cinderbackup_types.go
  api/v1beta1/cinderscheduler_types.go
  api/v1beta1/cindervolume_types.go
  config/crd/bases/cinder.openstack.org_cinderapis.yaml
  config/crd/bases/cinder.openstack.org_cinderbackups.yaml
  config/crd/bases/cinder.openstack.org_cinders.yaml
  config/crd/bases/cinder.openstack.org_cinderschedulers.yaml
  config/crd/bases/cinder.openstack.org_cindervolumes.yaml
  controllers/cinder_controller.go
  templates/cinder/bin/init.sh
  templates/cinder/config/cinder-api-config.json
  templates/cinder/config/cinder-backup-config.json
  templates/cinder/config/cinder-scheduler-config.json
  templates/cinder/config/cinder-volume-config.json
  templates/cinder/config/cinder.conf
  templates/cinder/config/db-sync-config.json
  templates/cinder/config/logging.conf
Labels: lgtm, needs-ok-to-test, approved

#13 Cleanup httpd.conf
  templates/cinder/config/httpd.conf
Labels: lgtm, approved, ok-to-test

#14 Fix ConfigMap generation ignores failures
  controllers/cinder_controller.go
Labels: lgtm, approved, ok-to-test

#15 Fix debug mode
  pkg/cinderapi/deployment.go
  pkg/cinderbackup/statefulset.go
  pkg/cinderscheduler/statefulset.go
  pkg/cindervolume/statefulset.go
Labels: lgtm, approved, ok-to-test

#16 Log the Cinder CR instance name
  controllers/cinder_controller.go
  controllers/cinderapi_controller.go
  controllers/cinderbackup_controller.go
  controllers/cinderscheduler_controller.go
  controllers/cindervolume_controller.go
Labels: lgtm, approved, ok-to-test

#17 Get Service by name using keystone
  controllers/cinderapi_controller.go
Labels: lgtm, approved

#11 Rework CephBackend and rely to the lib-common Ceph Module
  api/go.mod
  api/go.sum
  api/v1beta1/cinder_types.go
  api/v1beta1/common_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cinder.openstack.org_cinders.yaml
  controllers/cinder_controller.go
  go.mod
  go.sum
  pkg/cinder/ceph_backend.go
  templates/cinder/config/ceph.client.openstack.keyring
  templates/cinder/config/ceph.conf
Labels: lgtm, approved

#19 Fix Ceph templates
  templates/cinder/config/cinder-volume-config.json
  templates/cinder/config/cinder.conf
Labels: lgtm

#18 Always attempt to remove finalizer on delete
  controllers/cinderapi_controller.go
Labels: lgtm, approved

#23 Run go mod tidy within /api
  api/go.mod
  api/go.sum
Labels: lgtm, approved

#24 Rename keystone package name to keystonev1
  controllers/cinder_controller.go
  controllers/cinderapi_controller.go
Labels: lgtm, approved

#25 Minor updates for SDK 1.23.0
  .github/workflows/build-cinder-operator.yaml
  Makefile
  config/default/manager_auth_proxy_patch.yaml
Labels: lgtm, approved

#26 Add dependabot.yml
  .github/dependabot.yml
Labels: lgtm, approved

#31 Fix backups
  pkg/cinderbackup/statefulset.go
  templates/cinder/config/cinder-backup-config.json
Labels: lgtm, approved

#32 Use keystone catalog info for Glance
  templates/cinder/config/cinder.conf
Labels: lgtm, approved

#33 Reduce memory consumption in Cinder services
  pkg/cinderbackup/statefulset.go
  pkg/cindervolume/statefulset.go
Labels: lgtm, approved

#36 Using internal Glance URL
  templates/cinder/config/cinder.conf
Labels: lgtm, approved

#20 Improve the Cinder Probes
  pkg/cinderbackup/statefulset.go
  pkg/cinderscheduler/statefulset.go
  pkg/cindervolume/statefulset.go
  templates/cinder/bin/healthcheck.py
  templates/cinder/bin/healthcheck.sh
Labels: lgtm, approved

#38 Debug improvements
  api/v1beta1/cinderapi_types.go
  api/v1beta1/cinderbackup_types.go
  api/v1beta1/cinderscheduler_types.go
  api/v1beta1/cindervolume_types.go
  api/v1beta1/common_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cinder.openstack.org_cinderapis.yaml
  config/crd/bases/cinder.openstack.org_cinderbackups.yaml
  config/crd/bases/cinder.openstack.org_cinders.yaml
  config/crd/bases/cinder.openstack.org_cinderschedulers.yaml
  config/crd/bases/cinder.openstack.org_cindervolumes.yaml
  pkg/cinder/dbsync.go
  pkg/cinder/initcontainer.go
  pkg/cinderapi/deployment.go
  pkg/cinderbackup/statefulset.go
  pkg/cinderscheduler/statefulset.go
  pkg/cindervolume/statefulset.go
Labels: lgtm, approved

#45 update to use new KeystoneEndpoint
  api/go.mod
  api/go.sum
  config/rbac/role.yaml
  controllers/cinder_controller.go
  controllers/cinderapi_controller.go
  go.mod
  go.sum
Labels: lgtm, approved

#47 Simplify resource cleanup
  controllers/cinderapi_controller.go
Labels: lgtm, approved

#44 Drop registry.redhat.io login from github action
  .github/workflows/build-cinder-operator.yaml
Labels: lgtm, approved

#37 Update makefile
  Makefile
  config/default/kustomization.yaml
  config/dev/kustomization.yaml
  config/manager/manager.yaml
Labels: lgtm, approved

#46 Copy rendered CRD files dir to /api/bases in make manifests
  Makefile
  api/bases/cinder.openstack.org_cinderapis.yaml
  api/bases/cinder.openstack.org_cinderbackups.yaml
  api/bases/cinder.openstack.org_cinders.yaml
  api/bases/cinder.openstack.org_cinderschedulers.yaml
  api/bases/cinder.openstack.org_cindervolumes.yaml
Labels: lgtm, approved

#50 Drop controller:latest logic from create_bundle.sh
  .github/create_bundle.sh
Labels: lgtm, approved
