Repository openstack-k8s-operators/cinder-operator, pull requests merged in 2023-03, with the labels that each got.

#150 remove no longer required replace in go.mod
  go.mod
Labels: lgtm, approved

#148 Webhook for default images
  PROJECT
  api/bases/cinder.openstack.org_cinderapis.yaml
  api/bases/cinder.openstack.org_cinderbackups.yaml
  api/bases/cinder.openstack.org_cinders.yaml
  api/bases/cinder.openstack.org_cinderschedulers.yaml
  api/bases/cinder.openstack.org_cindervolumes.yaml
  api/go.mod
  api/go.sum
  api/v1beta1/cinder_webhook.go
  api/v1beta1/cinderapi_types.go
  api/v1beta1/cinderbackup_types.go
  api/v1beta1/cinderscheduler_types.go
  api/v1beta1/cindervolume_types.go
  api/v1beta1/webhook_suite_test.go
  api/v1beta1/zz_generated.deepcopy.go
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/bases/cinder.openstack.org_cinderapis.yaml
  config/crd/bases/cinder.openstack.org_cinderbackups.yaml
  config/crd/bases/cinder.openstack.org_cinders.yaml
  config/crd/bases/cinder.openstack.org_cinderschedulers.yaml
  config/crd/bases/cinder.openstack.org_cindervolumes.yaml
  config/default/kustomization.yaml
  config/default/manager_default_images.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_service.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  main.go
Labels: lgtm, approved

#107 Use own user to send admin requests to nova
  templates/cinder/bin/init.sh
  templates/cinder/config/cinder.conf
Labels: lgtm, approved, ok-to-test

#151 Add omitempty to CinderVolumeSpec
  api/v1beta1/cinder_types.go
Labels: lgtm, approved

#153 Remove description from Cinder CRD
  Makefile
  api/bases/cinder.openstack.org_cinderapis.yaml
  api/bases/cinder.openstack.org_cinderbackups.yaml
  api/bases/cinder.openstack.org_cinders.yaml
  api/bases/cinder.openstack.org_cinderschedulers.yaml
  api/bases/cinder.openstack.org_cindervolumes.yaml
  config/crd/bases/cinder.openstack.org_cinderapis.yaml
  config/crd/bases/cinder.openstack.org_cinderbackups.yaml
  config/crd/bases/cinder.openstack.org_cinders.yaml
  config/crd/bases/cinder.openstack.org_cinderschedulers.yaml
  config/crd/bases/cinder.openstack.org_cindervolumes.yaml
Labels: lgtm, approved

#154 Fix use of 'ServiceUser' in template
  templates/cinder/config/cinder.conf
Labels: lgtm, approved

#149 Use constant to define restart policy
  pkg/cinder/dbsync.go
Labels: lgtm, approved

#152 Bump operator-lint to 0.3.0 and fix findings
  Makefile
  api/bases/cinder.openstack.org_cinderapis.yaml
  api/bases/cinder.openstack.org_cinderbackups.yaml
  api/bases/cinder.openstack.org_cinders.yaml
  api/bases/cinder.openstack.org_cinderschedulers.yaml
  api/bases/cinder.openstack.org_cindervolumes.yaml
  api/v1beta1/cinder_types.go
  api/v1beta1/cinderapi_types.go
  api/v1beta1/cinderbackup_types.go
  api/v1beta1/cinderscheduler_types.go
  api/v1beta1/cindervolume_types.go
  api/v1beta1/common_types.go
  config/certmanager/kustomizeconfig.yaml
  config/crd/bases/cinder.openstack.org_cinderapis.yaml
  config/crd/bases/cinder.openstack.org_cinderbackups.yaml
  config/crd/bases/cinder.openstack.org_cinders.yaml
  config/crd/bases/cinder.openstack.org_cinderschedulers.yaml
  config/crd/bases/cinder.openstack.org_cindervolumes.yaml
Labels: lgtm, approved

#119 Add basic KUTTL tests for Cinder Operator
  kuttl-test.yaml
  tests/kuttl/common/assert_sample_deployment.yaml
  tests/kuttl/tests/cinder_scale/01-assert.yaml
  tests/kuttl/tests/cinder_scale/01-deploy-cinder.yaml
  tests/kuttl/tests/cinder_scale/05-cleanup-cinder.yaml
  tests/kuttl/tests/cinder_scale/05-errors.yaml
Labels: lgtm, needs-ok-to-test, approved

#155 Support local webhooks
  Makefile
  hack/configure_local_webhook.sh
Labels: lgtm, approved

#108 Revamp the service configuration process
  api/bases/cinder.openstack.org_cinderapis.yaml
  api/bases/cinder.openstack.org_cinderbackups.yaml
  api/bases/cinder.openstack.org_cinders.yaml
  api/bases/cinder.openstack.org_cinderschedulers.yaml
  api/bases/cinder.openstack.org_cindervolumes.yaml
  api/v1beta1/cinder_types.go
  api/v1beta1/cinderapi_types.go
  api/v1beta1/cinderbackup_types.go
  api/v1beta1/cinderscheduler_types.go
  api/v1beta1/cindervolume_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cinder.openstack.org_cinderapis.yaml
  config/crd/bases/cinder.openstack.org_cinderbackups.yaml
  config/crd/bases/cinder.openstack.org_cinders.yaml
  config/crd/bases/cinder.openstack.org_cinderschedulers.yaml
  config/crd/bases/cinder.openstack.org_cindervolumes.yaml
  controllers/cinder_controller.go
  controllers/cinderapi_controller.go
  controllers/cinderbackup_controller.go
  controllers/cinderscheduler_controller.go
  controllers/cindervolume_controller.go
  pkg/cinder/volumes.go
  pkg/cinderapi/deployment.go
  pkg/cinderapi/volumes.go
  pkg/cinderbackup/statefulset.go
  pkg/cinderbackup/volumes.go
  pkg/cinderscheduler/statefulset.go
  pkg/cinderscheduler/volumes.go
  pkg/cindervolume/statefulset.go
  pkg/cindervolume/volumes.go
  templates/cinder/bin/healthcheck.py
  templates/cinder/bin/init.sh
  templates/cinder/config/cinder-api-config.json
  templates/cinder/config/cinder-backup-config.json
  templates/cinder/config/cinder-scheduler-config.json
  templates/cinder/config/cinder-volume-config.json
  templates/cinder/config/cinder.conf
  templates/cinder/config/db-sync-config.json
  templates/cinder/config/nfs_shares
  templates/common/10-cinder_wsgi.conf
Labels: lgtm, approved

#158 Infer enabled_backends if it's not specified in the CR
  controllers/cindervolume_controller.go
Labels: lgtm, approved

#161 Get overall state from sub resources Ready state
  api/v1beta1/cinder_types.go
Labels: lgtm, approved

#169 Add NFS backend config sample
  config/samples/backends/nfs/backend.yaml
  config/samples/backends/nfs/cinder-volume-nfs-secrets.yaml
  config/samples/backends/nfs/kustomization.yaml
Labels: lgtm, approved

#170 Clean up cinder-volume deployments
  controllers/cinder_controller.go
Labels: lgtm, approved

#167 Fix iscsi lvm
  config/samples/backends/lvm-iscsi/backend.yaml
  config/samples/backends/lvm-iscsi/iscsid.yaml
  config/samples/backends/lvm-iscsi/kustomization.yaml
  config/samples/backends/lvm-iscsi/lvm.yaml
  config/samples/backends/lvm-iscsi/multipathd.yaml
  pkg/cinder/volumes.go
  pkg/cinderbackup/statefulset.go
  pkg/cindervolume/statefulset.go
  templates/cinder/bin/run-on-host
  templates/cinder/config/cinder-backup-config.json
  templates/cinder/config/cinder-volume-config.json
Labels: lgtm, approved
