Repository openstack-k8s-operators/cinder-operator, pull requests merged in 2024-02, with the labels that each got.

#306 [tlse] tls for Cinder pod configuration
  api/bases/cinder.openstack.org_cinderapis.yaml
  api/bases/cinder.openstack.org_cinderbackups.yaml
  api/bases/cinder.openstack.org_cinders.yaml
  api/bases/cinder.openstack.org_cinderschedulers.yaml
  api/bases/cinder.openstack.org_cindervolumes.yaml
  api/v1beta1/cinderapi_types.go
  api/v1beta1/cinderbackup_types.go
  api/v1beta1/cinderscheduler_types.go
  api/v1beta1/cindervolume_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/cinder.openstack.org_cinderapis.yaml
  config/crd/bases/cinder.openstack.org_cinderbackups.yaml
  config/crd/bases/cinder.openstack.org_cinders.yaml
  config/crd/bases/cinder.openstack.org_cinderschedulers.yaml
  config/crd/bases/cinder.openstack.org_cindervolumes.yaml
  config/samples/cinder_v1beta1_cinder_tls.yaml
  config/samples/cinder_v1beta1_cinderapi.yaml
  controllers/cinder_controller.go
  controllers/cinderapi_controller.go
  controllers/cinderbackup_controller.go
  controllers/cinderscheduler_controller.go
  controllers/cindervolume_controller.go
  go.mod
  pkg/cinder/cronjob.go
  pkg/cinder/dbsync.go
  pkg/cinderapi/statefuleset.go
  pkg/cinderbackup/statefulset.go
  pkg/cinderscheduler/statefulset.go
  pkg/cindervolume/statefulset.go
  templates/cinder/config/10-cinder_wsgi.conf
  templates/cinder/config/cinder-api-config.json
  templates/cinder/config/ssl.conf
  test/functional/base_test.go
  test/functional/cinder_controller_test.go
  test/functional/cinder_test_data.go
  test/kuttl/common/assert_tls_cert.yaml
  test/kuttl/common/assert_tls_sample_deployment.yaml
  test/kuttl/common/tls_ca_bundle.yaml
  test/kuttl/common/tls_cert_cinder-internal-svc.yaml
  test/kuttl/common/tls_cert_cinder-public-svc.yaml
  test/kuttl/tests/cinder_tls/00-assert.yaml
  test/kuttl/tests/cinder_tls/00-tls_ca_bundle.yaml
  test/kuttl/tests/cinder_tls/00-tls_cert_cinder-internal-svc.yaml
  test/kuttl/tests/cinder_tls/00-tls_cert_cinder-public-svc.yaml
  test/kuttl/tests/cinder_tls/01-assert.yaml
  test/kuttl/tests/cinder_tls/01-deploy-cinder.yaml
  test/kuttl/tests/cinder_tls/05-cleanup-cinder.yaml
  test/kuttl/tests/cinder_tls/05-errors.yaml
  test/kuttl/tests/cinder_tls/deploy/kustomization.yaml
Labels: lgtm, approved

#332 Set pod affinity to spread services across OCP workers
  api/v1beta1/cinder_webhook.go
  controllers/cinderapi_controller.go
  controllers/cinderbackup_controller.go
  controllers/cinderscheduler_controller.go
  controllers/cindervolume_controller.go
  pkg/cinder/funcs.go
  pkg/cinderapi/const.go
  pkg/cinderapi/statefuleset.go
  pkg/cinderbackup/const.go
  pkg/cinderbackup/statefulset.go
  pkg/cinderscheduler/const.go
  pkg/cinderscheduler/statefulset.go
  pkg/cindervolume/const.go
  pkg/cindervolume/statefulset.go
  test/kuttl/common/assert_sample_deployment.yaml
Labels: lgtm, approved

#333 Backend Samples: place on worker nodes
  config/samples/backends/bases/iscsid/iscsid.yaml
  config/samples/backends/bases/lvm/lvm.yaml
  config/samples/backends/bases/multipathd/multipathd.yaml
  config/samples/backends/bases/nvmeof/nvme-fabrics.yaml
Labels: lgtm, approved

#335 Revert "Backend Samples: place on worker nodes"
  config/samples/backends/bases/iscsid/iscsid.yaml
  config/samples/backends/bases/lvm/lvm.yaml
  config/samples/backends/bases/multipathd/multipathd.yaml
  config/samples/backends/bases/nvmeof/nvme-fabrics.yaml
Labels: lgtm, approved

#337 Unique LeaderElectionID
  api/bases/cinder.openstack.org_cinderapis.yaml
  api/bases/cinder.openstack.org_cinderbackups.yaml
  api/bases/cinder.openstack.org_cinders.yaml
  api/bases/cinder.openstack.org_cinderschedulers.yaml
  api/bases/cinder.openstack.org_cindervolumes.yaml
  api/go.mod
  api/go.sum
  config/crd/bases/cinder.openstack.org_cinderapis.yaml
  config/crd/bases/cinder.openstack.org_cinderbackups.yaml
  config/crd/bases/cinder.openstack.org_cinders.yaml
  config/crd/bases/cinder.openstack.org_cinderschedulers.yaml
  config/crd/bases/cinder.openstack.org_cindervolumes.yaml
  main.go
Labels: approved

#340 [renovate]Remove golang constraint
  renovate.json
Labels: lgtm, approved

#339 Bump golangci-lint
  .golangci.yaml
  .pre-commit-config.yaml
Labels: lgtm, approved

#331 Samples: Add Dell PowerMax ISCSI backend samples
  config/samples/backends/README.md
  config/samples/backends/dell/powermax/iscsi/backend.yaml
  config/samples/backends/dell/powermax/iscsi/cinder-volume-powermax-secrets.yaml
  config/samples/backends/dell/powermax/iscsi/kustomization.yaml
Labels: lgtm, approved, ok-to-test, tide/merge-method-squash

#350 Remove notifications TODO
  templates/cinder/config/00-global-defaults.conf
Labels: lgtm, approved

#347 Regenerate go.mod indirect dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: lgtm, approved
